name: Build and deploy

on:
  pull_request:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install pandoc
        run: |
          sudo apt-get install -y pandoc
      - name: run build script
        run: |
          /bin/bash ./build --noconfirm
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-out
          cname: legal.valoresports.com
          publish_branch: prod-build
