name: Build and deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: collate .tex files
        run: |
          mkdir tex
          find -type f -iname "*.tex" -exec mv {} tex/. \;
          cd tex
      - name: convert tex tiles to PDFs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
      - name: collate PDFs into public dir
        run: |
          cd ..
          mkdir -p public/pdf
          find -type f -iname "*.pdf" -exec mv {} public/pdf/
          cd public/pdf
          tree -H . -o index.html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: legal.valoresports.com
          publish_branch: prod-build
