name: Build and deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: collate .tex files
        run: |
          find -type f -iname "*.tex" -exec mv {} . \;
      - name: convert .tex tiles to PDFs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
      - name: collate PDFs into public dir
        run: |
          mkdir -p public/pdf
          find -type f -iname "*.pdf" -exec mv {} public/pdf/. \;
          cd public/pdf
          tree -H . -o index.html
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
